prompt_order = [
    "username",
    "hostname",
    "kubernetes",
    "directory",
    "git_branch",
    "git_state",
    "git_status",
    "package",
    "dotnet",
    "golang",
    "haskell",
    "java",
    "nodejs",
    "python",
    "ruby",
    "rust",
    "nix_shell",
    "memory_usage",
    "aws",
    "env_var",
    "battery",
    "cmd_duration",
    "time",
    "line_break",
    "jobs",
    "character",
]

[time]
disabled = false
#format = "🕙[ %T %D ]"
format = "🕙[ %T %v ]"

#[character]
#symbol = "⮞"
#vicmd_symbol = "⮜"

