(add-to-list 'load-path (expand-file-name "personal/lisp" user-emacs-directory))

(require 'init-use-package)
(require 'init-ui)
(require 'init-prelude)
(require 'init-projectile)
(require 'init-hydra)
(require 'init-modeline)
(require 'init-dashboard)
(require 'init-completion)
(require 'init-lisp)
(require 'init-clojure)
(require 'init-lsp)
(require 'init-git)
(require 'init-mac)
(require 'init-misc)

(add-hook 'after-init-hook '(lambda ()
                              (setq gc-cons-threshold (* 100 1024 1024)
                                    gc-cons-percentage 0.1)))

(global-unset-key (kbd "<left>"))
(global-unset-key (kbd "<right>"))
(global-unset-key (kbd "<up>"))
(global-unset-key (kbd "<down>"))
(global-unset-key (kbd "<C-left>"))
(global-unset-key (kbd "<C-right>"))
(global-unset-key (kbd "<C-up>"))
(global-unset-key (kbd "<C-down>"))
(global-unset-key (kbd "<M-left>"))
(global-unset-key (kbd "<M-right>"))
(global-unset-key (kbd "<M-up>"))
(global-unset-key (kbd "<M-down>"))
(global-unset-key (kbd "<delete>"))
(global-unset-key (kbd "<deletechar>"))

