(add-to-list 'load-path (expand-file-name "personal/lisp" user-emacs-directory))

;; TODO persp/perspective/projectile-persp, dired/counsel-dired/..?, lsp-ivy
(require 'init-use-package)
(require 'init-prelude)
(require 'init-ui)
(require 'init-hydra)
(require 'init-modeline)
;(require 'init-dashboard)
(require 'init-completion)
(require 'init-lisp)
(require 'init-clojure)
(require 'init-lsp)

(global-unset-key (kbd "<left>"))
(global-unset-key (kbd "<right>"))
(global-unset-key (kbd "<up>"))
(global-unset-key (kbd "<down>"))
(global-unset-key (kbd "<C-left>"))
(global-unset-key (kbd "<C-right>"))
(global-unset-key (kbd "<C-up>"))
(global-unset-key (kbd "<C-down>"))
(global-unset-key (kbd "<M-left>"))
(global-unset-key (kbd "<M-right>"))
(global-unset-key (kbd "<M-up>"))
(global-unset-key (kbd "<M-down>"))
(global-unset-key (kbd "<delete>"))
(global-unset-key (kbd "<deletechar>"))

