keys:
  - &admin_djm age180j2e0jxu2vpwz4qkz3ydfwlfxydvznzyy4p7rp8n760fst6yffqh43t8k
  - &server_edrahil age1tjfctwnwldmyxnu6qmeufgr9l79vyzmrs7fy58v3d0qj4x4nhqhq2gjmlp
  - &server_djmuk2 age17j56andser5ddtlfunm35m25xueua4djh9glxlscfcet8865yv9s5aqvla
creation_rules:
  - path_regex: ^hosts/nixos/edrahil/secrets/sops/([^/]+/)?[^/]+\.yml$
    key_groups:
    - age:
      - *server_edrahil
      - *admin_djm
  - path_regex: ^hosts/nixos/djmuk2/secrets/sops/([^/]+/)?[^/]+\.yml$
    key_groups:
    - age:
      - *server_djmuk2
      - *admin_djm
  - path_regex: ^hosts/home-manager/modules/home-secrets/secrets/sops/([^/]+/)?[^/]+\.yml$
    key_groups:
    - age:
      - *admin_djm
